export const TIPOS = ['normal','fire','water','grass','electric','ice','fighting','poison','ground','flying','psychic','bug','rock','ghost','dragon','dark','steel','fairy']

export const TIPO_COLORS = {
  normal:'#9a9a9a', fire:'#ff4422', water:'#2288ff', grass:'#33aa33',
  electric:'#ddbb00', ice:'#55ccee', fighting:'#bb3311', poison:'#9933bb',
  ground:'#bb8833', flying:'#7799ee', psychic:'#ff4488', bug:'#77aa11',
  rock:'#aaaa55', ghost:'#6655aa', dragon:'#4433dd', dark:'#665544',
  steel:'#8899aa', fairy:'#ee88bb'
}

export const EFF_TABLE = [
  [1,1,1,1,1,1,1,1,1,1,1,1,0.5,0,1,1,0.5,1],
  [1,0.5,0.5,2,1,2,1,1,1,1,1,2,0.5,1,0.5,1,2,1],
  [1,2,0.5,0.5,1,1,1,1,2,1,1,1,2,1,0.5,1,1,1],
  [1,0.5,2,0.5,1,1,1,0.5,2,0.5,1,0.5,2,1,0.5,1,0.5,1],
  [1,1,2,0.5,0.5,1,1,1,0,2,1,1,1,1,0.5,1,1,1],
  [1,0.5,0.5,2,1,0.5,1,1,2,2,1,1,1,1,2,1,0.5,1],
  [2,1,1,1,1,2,1,0.5,1,0.5,0.5,0.5,2,0,1,2,2,0.5],
  [1,1,1,2,1,1,1,0.5,0.5,1,1,1,0.5,0.5,1,1,0.5,2],
  [1,2,1,0.5,2,1,1,2,1,0,1,0.5,2,1,1,1,2,1],
  [1,1,1,2,0.5,1,2,1,1,1,1,2,0.5,1,1,1,0.5,1],
  [1,1,1,1,1,1,2,2,1,1,0.5,1,1,1,1,0,0.5,1],
  [1,0.5,1,2,1,1,0.5,0.5,1,0.5,2,1,1,0.5,1,2,0.5,0.5],
  [1,2,1,1,1,2,0.5,1,0.5,2,1,2,1,1,1,1,0.5,1],
  [0,1,1,1,1,1,1,1,1,1,2,1,1,2,1,0.5,1,1],
  [1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,0.5,0],
  [1,1,1,1,1,1,0.5,1,1,1,2,1,1,2,1,0.5,1,0.5],
  [1,0.5,0.5,0.5,0.5,2,1,1,1,0.5,0.5,0.5,2,1,0.5,1,0.5,2],
  [1,0.5,1,1,1,1,2,0.5,1,1,1,1,1,1,2,2,0.5,0.5],
]

export const TIPO_IDX = Object.fromEntries(TIPOS.map((t,i) => [t,i]))

export function getEff(atkType, defTypes) {
  const a = TIPO_IDX[atkType]
  if (a === undefined) return 1
  return defTypes.reduce((mult, dt) => {
    const d = TIPO_IDX[dt]
    return d !== undefined ? mult * EFF_TABLE[a][d] : mult
  }, 1)
}

export const POKEDEX = [
  // Gen 1
  {name:'Venusaur',types:['grass','poison']},
  {name:'Charizard',types:['fire','flying']},
  {name:'Blastoise',types:['water']},
  {name:'Beedrill',types:['bug','poison']},
  {name:'Pidgeot',types:['normal','flying']},
  {name:'Arbok',types:['poison']},
  {name:'Pikachu',types:['electric']},
  {name:'Raichu',types:['electric']},
  {name:'Raichu-Alola',types:['electric','psychic']},
  {name:'Clefable',types:['fairy']},
  {name:'Ninetales',types:['fire']},
  {name:'Ninetales-Alola',types:['ice','fairy']},
  {name:'Arcanine',types:['fire']},
  {name:'Arcanine-Hisui',types:['fire','rock']},
  {name:'Alakazam',types:['psychic']},
  {name:'Machamp',types:['fighting']},
  {name:'Victreebel',types:['grass','poison']},
  {name:'Slowbro',types:['water','psychic']},
  {name:'Slowbro-Galarian',types:['poison','psychic']},
  {name:'Gengar',types:['ghost','poison']},
  {name:'Kangaskhan',types:['normal']},
  {name:'Starmie',types:['water','psychic']},
  {name:'Pinsir',types:['bug']},
  {name:'Tauros',types:['normal']},
  {name:'Tauros-Paldea-Combat',types:['fighting']},
  {name:'Tauros-Paldea-Blaze',types:['fighting','fire']},
  {name:'Tauros-Paldea-Aqua',types:['fighting','water']},
  {name:'Gyarados',types:['water','flying']},
  {name:'Ditto',types:['normal']},
  {name:'Vaporeon',types:['water']},
  {name:'Jolteon',types:['electric']},
  {name:'Flareon',types:['fire']},
  {name:'Aerodactyl',types:['rock','flying']},
  {name:'Snorlax',types:['normal']},
  {name:'Dragonite',types:['dragon','flying']},
  // Gen 2
  {name:'Meganium',types:['grass']},
  {name:'Typhlosion',types:['fire']},
  {name:'Typhlosion-Hisui',types:['fire','ghost']},
  {name:'Feraligatr',types:['water']},
  {name:'Ariados',types:['bug','poison']},
  {name:'Ampharos',types:['electric']},
  {name:'Azumarill',types:['water','fairy']},
  {name:'Politoed',types:['water']},
  {name:'Espeon',types:['psychic']},
  {name:'Umbreon',types:['dark']},
  {name:'Slowking',types:['water','psychic']},
  {name:'Slowking-Galarian',types:['poison','psychic']},
  {name:'Forretress',types:['bug','steel']},
  {name:'Steelix',types:['steel','ground']},
  {name:'Scizor',types:['bug','steel']},
  {name:'Heracross',types:['bug','fighting']},
  {name:'Skarmory',types:['steel','flying']},
  {name:'Houndoom',types:['dark','fire']},
  {name:'Tyranitar',types:['rock','dark']},
  // Gen 3
  {name:'Pelipper',types:['water','flying']},
  {name:'Gardevoir',types:['psychic','fairy']},
  {name:'Sableye',types:['dark','ghost']},
  {name:'Aggron',types:['steel','rock']},
  {name:'Medicham',types:['fighting','psychic']},
  {name:'Manectric',types:['electric']},
  {name:'Sharpedo',types:['water','dark']},
  {name:'Camerupt',types:['fire','ground']},
  {name:'Torkoal',types:['fire']},
  {name:'Altaria',types:['dragon','flying']},
  {name:'Milotic',types:['water']},
  {name:'Castform',types:['normal']},
  {name:'Banette',types:['ghost']},
  {name:'Chimecho',types:['psychic']},
  {name:'Absol',types:['dark']},
  {name:'Glalie',types:['ice']},
  // Gen 4
  {name:'Torterra',types:['grass','ground']},
  {name:'Infernape',types:['fire','fighting']},
  {name:'Empoleon',types:['water','steel']},
  {name:'Luxray',types:['electric']},
  {name:'Roserade',types:['grass','poison']},
  {name:'Rampardos',types:['rock']},
  {name:'Bastiodon',types:['rock','steel']},
  {name:'Lopunny',types:['normal']},
  {name:'Spiritomb',types:['ghost','dark']},
  {name:'Garchomp',types:['dragon','ground']},
  {name:'Lucario',types:['fighting','steel']},
  {name:'Hippowdon',types:['ground']},
  {name:'Toxicroak',types:['poison','fighting']},
  {name:'Abomasnow',types:['grass','ice']},
  {name:'Weavile',types:['dark','ice']},
  {name:'Rhyperior',types:['ground','rock']},
  {name:'Leafeon',types:['grass']},
  {name:'Glaceon',types:['ice']},
  {name:'Gliscor',types:['ground','flying']},
  {name:'Mamoswine',types:['ice','ground']},
  {name:'Gallade',types:['psychic','fighting']},
  {name:'Froslass',types:['ice','ghost']},
  {name:'Rotom',types:['electric','ghost']},
  {name:'Rotom-Heat',types:['electric','fire']},
  {name:'Rotom-Wash',types:['electric','water']},
  {name:'Rotom-Frost',types:['electric','ice']},
  {name:'Rotom-Fan',types:['electric','flying']},
  {name:'Rotom-Mow',types:['electric','grass']},
  // Gen 5
  {name:'Serperior',types:['grass']},
  {name:'Emboar',types:['fire','fighting']},
  {name:'Samurott',types:['water']},
  {name:'Samurott-Hisui',types:['water','dark']},
  {name:'Watchog',types:['normal']},
  {name:'Liepard',types:['dark']},
  {name:'Simisage',types:['grass']},
  {name:'Simisear',types:['fire']},
  {name:'Simipour',types:['water']},
  {name:'Excadrill',types:['ground','steel']},
  {name:'Audino',types:['normal']},
  {name:'Conkeldurr',types:['fighting']},
  {name:'Whimsicott',types:['grass','fairy']},
  {name:'Krookodile',types:['ground','dark']},
  {name:'Garbodor',types:['poison']},
  {name:'Cofagrigus',types:['ghost']},
  {name:'Zoroark',types:['dark']},
  {name:'Zoroark-Hisui',types:['normal','ghost']},
  {name:'Reuniclus',types:['psychic']},
  {name:'Vanilluxe',types:['ice']},
  {name:'Emolga',types:['electric','flying']},
  {name:'Chandelure',types:['ghost','fire']},
  {name:'Beartic',types:['ice']},
  {name:'Stunfisk',types:['ground','electric']},
  {name:'Stunfisk-Galarian',types:['ground','steel']},
  {name:'Golurk',types:['ground','ghost']},
  {name:'Hydreigon',types:['dark','dragon']},
  {name:'Volcarona',types:['bug','fire']},
  // Gen 6
  {name:'Chesnaught',types:['grass','fighting']},
  {name:'Delphox',types:['fire','psychic']},
  {name:'Greninja',types:['water','dark']},
  {name:'Diggersby',types:['normal','ground']},
  {name:'Talonflame',types:['fire','flying']},
  {name:'Vivillon',types:['bug','flying']},
  {name:'Floette',types:['fairy']},
  {name:'Florges',types:['fairy']},
  {name:'Pangoro',types:['fighting','dark']},
  {name:'Furfrou',types:['normal']},
  {name:'Meowstic-M',types:['psychic']},
  {name:'Meowstic-F',types:['psychic']},
  {name:'Aegislash',types:['steel','ghost']},
  {name:'Aromatisse',types:['fairy']},
  {name:'Slurpuff',types:['fairy']},
  {name:'Clawitzer',types:['water']},
  {name:'Heliolisk',types:['electric','normal']},
  {name:'Tyrantrum',types:['rock','dragon']},
  {name:'Aurorus',types:['rock','ice']},
  {name:'Sylveon',types:['fairy']},
  {name:'Hawlucha',types:['fighting','flying']},
  {name:'Dedenne',types:['electric','fairy']},
  {name:'Goodra',types:['dragon']},
  {name:'Goodra-Hisui',types:['steel','dragon']},
  {name:'Klefki',types:['steel','fairy']},
  {name:'Trevenant',types:['ghost','grass']},
  {name:'Gourgeist',types:['ghost','grass']},
  {name:'Avalugg',types:['ice']},
  {name:'Avalugg-Hisui',types:['ice','rock']},
  {name:'Noivern',types:['flying','dragon']},
  // Gen 7
  {name:'Decidueye',types:['grass','ghost']},
  {name:'Decidueye-Hisui',types:['grass','fighting']},
  {name:'Incineroar',types:['fire','dark']},
  {name:'Primarina',types:['water','fairy']},
  {name:'Toucannon',types:['normal','flying']},
  {name:'Crabominable',types:['fighting','ice']},
  {name:'Lycanroc',types:['rock']},
  {name:'Lycanroc-Midnight',types:['rock']},
  {name:'Lycanroc-Dusk',types:['rock']},
  {name:'Toxapex',types:['poison','water']},
  {name:'Mudsdale',types:['ground']},
  {name:'Araquanid',types:['water','bug']},
  {name:'Salazzle',types:['poison','fire']},
  {name:'Tsareena',types:['grass']},
  {name:'Oranguru',types:['normal','psychic']},
  {name:'Passimian',types:['fighting']},
  {name:'Mimikyu',types:['ghost','fairy']},
  {name:'Drampa',types:['normal','dragon']},
  {name:'Kommo-o',types:['dragon','fighting']},
  // Gen 8
  {name:'Corviknight',types:['flying','steel']},
  {name:'Flapple',types:['grass','dragon']},
  {name:'Appletun',types:['grass','dragon']},
  {name:'Sandaconda',types:['ground']},
  {name:'Polteageist',types:['ghost']},
  {name:'Hatterene',types:['psychic','fairy']},
  {name:'Mr. Rime',types:['ice','psychic']},
  {name:'Runerigus',types:['ground','ghost']},
  {name:'Alcremie',types:['fairy']},
  {name:'Morpeko',types:['electric','dark']},
  {name:'Dragapult',types:['dragon','ghost']},
  // Hisui
  {name:'Wyrdeer',types:['normal','psychic']},
  {name:'Kleavor',types:['bug','rock']},
  {name:'Basculegion',types:['water','ghost']},
  {name:'Basculegion-F',types:['water','ghost']},
  {name:'Sneasler',types:['poison','fighting']},
  // Gen 9
  {name:'Meowscarada',types:['grass','dark']},
  {name:'Skeledirge',types:['fire','ghost']},
  {name:'Quaquaval',types:['water','fighting']},
  {name:'Maushold',types:['normal']},
  {name:'Garganacl',types:['rock']},
  {name:'Armarouge',types:['fire','psychic']},
  {name:'Ceruledge',types:['fire','ghost']},
  {name:'Bellibolt',types:['electric']},
  {name:'Scovillain',types:['grass','fire']},
  {name:'Espathra',types:['psychic','flying']},
  {name:'Tinkaton',types:['fairy','steel']},
  {name:'Palafin',types:['water']},
  {name:'Orthworm',types:['steel']},
  {name:'Glimmora',types:['rock','poison']},
  {name:'Farigiraf',types:['normal','psychic']},
  {name:'Kingambit',types:['dark','steel']},
  {name:'Sinistcha',types:['grass','ghost']},
  {name:'Archaludon',types:['dragon','steel']},
  {name:'Hydrapple',types:['grass','dragon']},
]