export const TIPOS = ['normal','fire','water','grass','electric','ice','fighting','poison','ground','flying','psychic','bug','rock','ghost','dragon','dark','steel','fairy']

export const TIPO_COLORS = {
  normal:   '#9a9a9a', fire:     '#ff4422', water:    '#2288ff', grass:    '#33aa33',
  electric: '#ddbb00', ice:      '#55ccee', fighting: '#bb3311', poison:   '#9933bb',
  ground:   '#bb8833', flying:   '#7799ee', psychic:  '#ff4488', bug:      '#77aa11',
  rock:     '#aaaa55', ghost:    '#6655aa', dragon:   '#4433dd', dark:     '#665544',
  steel:    '#8899aa', fairy:    '#ee88bb',
}

export const EFF_TABLE = [
  [1,1,1,1,1,1,1,1,1,1,1,1,0.5,0,1,1,0.5,1],
  [1,0.5,0.5,2,1,2,1,1,1,1,1,2,0.5,1,0.5,1,2,1],
  [1,2,0.5,0.5,1,1,1,1,2,1,1,1,2,1,0.5,1,1,1],
  [1,0.5,2,0.5,1,1,1,0.5,2,0.5,1,0.5,2,1,0.5,1,0.5,1],
  [1,1,2,0.5,0.5,1,1,1,0,2,1,1,1,1,0.5,1,1,1],
  [1,0.5,0.5,2,1,0.5,1,1,2,2,1,1,1,1,2,1,0.5,1],
  [2,1,1,1,1,2,1,0.5,1,0.5,0.5,0.5,2,0,1,2,2,0.5],
  [1,1,1,2,1,1,1,0.5,0.5,1,1,1,0.5,0.5,1,1,0.5,2],
  [1,2,1,0.5,2,1,1,2,1,0,1,0.5,2,1,1,1,2,1],
  [1,1,1,2,0.5,1,2,1,1,1,1,2,0.5,1,1,1,0.5,1],
  [1,1,1,1,1,1,2,2,1,1,0.5,1,1,1,1,0,0.5,1],
  [1,0.5,1,2,1,1,0.5,0.5,1,0.5,2,1,1,0.5,1,2,0.5,0.5],
  [1,2,1,1,1,2,0.5,1,0.5,2,1,2,1,1,1,1,0.5,1],
  [0,1,1,1,1,1,1,1,1,1,2,1,1,2,1,0.5,1,1],
  [1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,0.5,0],
  [1,1,1,1,1,1,0.5,1,1,1,2,1,1,2,1,0.5,1,0.5],
  [1,0.5,0.5,0.5,0.5,2,1,1,1,0.5,0.5,0.5,2,1,0.5,1,0.5,2],
  [1,0.5,1,1,1,1,2,0.5,1,1,1,1,1,1,2,2,0.5,0.5],
]

export const TIPO_IDX = Object.fromEntries(TIPOS.map((t, i) => [t, i]))

export function getEff(atkType, defTypes) {
  const a = TIPO_IDX[atkType]
  if (a === undefined) return 1
  return defTypes.reduce((mult, dt) => {
    const d = TIPO_IDX[dt]
    return d !== undefined ? mult * EFF_TABLE[a][d] : mult
  }, 1)
}

// ─── SPRITES ─────────────────────────────────────────────────────────────────
// Uses PokeAPI raw sprites. spriteId = national dex number (or form ID for forms)
// ─────────────────────────────────────────────────────────────────────────────
export function getSpriteUrl(spriteId) {
  if (!spriteId) return null
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${spriteId}.png`
}

// ─── POKÉDEX ─────────────────────────────────────────────────────────────────
export const POKEDEX = [

  // ── Gen 1 ──────────────────────────────────────────────────────────────────
  { name: 'Venusaur',             types: ['grass','poison'],    spriteId: 3   },
  { name: 'Charizard',            types: ['fire','flying'],     spriteId: 6   },
  { name: 'Blastoise',            types: ['water'],             spriteId: 9   },
  { name: 'Beedrill',             types: ['bug','poison'],      spriteId: 15  },
  { name: 'Pidgeot',              types: ['normal','flying'],   spriteId: 18  },
  { name: 'Arbok',                types: ['poison'],            spriteId: 24  },
  { name: 'Pikachu',              types: ['electric'],          spriteId: 25  },
  { name: 'Raichu',               types: ['electric'],          spriteId: 26  },
  { name: 'Raichu-Alola',         types: ['electric','psychic'],spriteId: 10105 },
  { name: 'Clefable',             types: ['fairy'],             spriteId: 36  },
  { name: 'Ninetales',            types: ['fire'],              spriteId: 38  },
  { name: 'Ninetales-Alola',      types: ['ice','fairy'],       spriteId: 10104 },
  { name: 'Arcanine',             types: ['fire'],              spriteId: 59  },
  { name: 'Arcanine-Hisui',       types: ['fire','rock'],       spriteId: 59  },
  { name: 'Alakazam',             types: ['psychic'],           spriteId: 65  },
  { name: 'Machamp',              types: ['fighting'],          spriteId: 68  },
  { name: 'Victreebel',           types: ['grass','poison'],    spriteId: 71  },
  { name: 'Slowbro',              types: ['water','psychic'],   spriteId: 80  },
  { name: 'Slowbro-Galarian',     types: ['poison','psychic'],  spriteId: 10182 },
  { name: 'Gengar',               types: ['ghost','poison'],    spriteId: 94  },
  { name: 'Kangaskhan',           types: ['normal'],            spriteId: 115 },
  { name: 'Starmie',              types: ['water','psychic'],   spriteId: 121 },
  { name: 'Pinsir',               types: ['bug'],               spriteId: 127 },
  { name: 'Tauros',               types: ['normal'],            spriteId: 128 },
  { name: 'Tauros-Paldea-Combat', types: ['fighting'],          spriteId: 128 },
  { name: 'Tauros-Paldea-Blaze',  types: ['fighting','fire'],   spriteId: 128 },
  { name: 'Tauros-Paldea-Aqua',   types: ['fighting','water'],  spriteId: 128 },
  { name: 'Gyarados',             types: ['water','flying'],    spriteId: 130 },
  { name: 'Ditto',                types: ['normal'],            spriteId: 132 },
  { name: 'Vaporeon',             types: ['water'],             spriteId: 134 },
  { name: 'Jolteon',              types: ['electric'],          spriteId: 135 },
  { name: 'Flareon',              types: ['fire'],              spriteId: 136 },
  { name: 'Aerodactyl',           types: ['rock','flying'],     spriteId: 142 },
  { name: 'Snorlax',              types: ['normal'],            spriteId: 143 },
  { name: 'Dragonite',            types: ['dragon','flying'],   spriteId: 149 },

  // ── Gen 2 ──────────────────────────────────────────────────────────────────
  { name: 'Meganium',             types: ['grass'],             spriteId: 154 },
  { name: 'Typhlosion',           types: ['fire'],              spriteId: 157 },
  { name: 'Typhlosion-Hisui',     types: ['fire','ghost'],      spriteId: 157 },
  { name: 'Feraligatr',           types: ['water'],             spriteId: 160 },
  { name: 'Ariados',              types: ['bug','poison'],      spriteId: 168 },
  { name: 'Ampharos',             types: ['electric'],          spriteId: 181 },
  { name: 'Azumarill',            types: ['water','fairy'],     spriteId: 184 },
  { name: 'Politoed',             types: ['water'],             spriteId: 186 },
  { name: 'Espeon',               types: ['psychic'],           spriteId: 196 },
  { name: 'Umbreon',              types: ['dark'],              spriteId: 197 },
  { name: 'Slowking',             types: ['water','psychic'],   spriteId: 199 },
  { name: 'Slowking-Galarian',    types: ['poison','psychic'],  spriteId: 10183 },
  { name: 'Forretress',           types: ['bug','steel'],       spriteId: 205 },
  { name: 'Steelix',              types: ['steel','ground'],    spriteId: 208 },
  { name: 'Scizor',               types: ['bug','steel'],       spriteId: 212 },
  { name: 'Heracross',            types: ['bug','fighting'],    spriteId: 214 },
  { name: 'Skarmory',             types: ['steel','flying'],    spriteId: 227 },
  { name: 'Houndoom',             types: ['dark','fire'],       spriteId: 229 },
  { name: 'Tyranitar',            types: ['rock','dark'],       spriteId: 248 },

  // ── Gen 3 ──────────────────────────────────────────────────────────────────
  { name: 'Pelipper',             types: ['water','flying'],    spriteId: 279 },
  { name: 'Gardevoir',            types: ['psychic','fairy'],   spriteId: 282 },
  { name: 'Sableye',              types: ['dark','ghost'],      spriteId: 302 },
  { name: 'Aggron',               types: ['steel','rock'],      spriteId: 306 },
  { name: 'Medicham',             types: ['fighting','psychic'],spriteId: 308 },
  { name: 'Manectric',            types: ['electric'],          spriteId: 310 },
  { name: 'Sharpedo',             types: ['water','dark'],      spriteId: 319 },
  { name: 'Camerupt',             types: ['fire','ground'],     spriteId: 323 },
  { name: 'Torkoal',              types: ['fire'],              spriteId: 324 },
  { name: 'Altaria',              types: ['dragon','flying'],   spriteId: 334 },
  { name: 'Milotic',              types: ['water'],             spriteId: 350 },
  { name: 'Castform',             types: ['normal'],            spriteId: 351 },
  { name: 'Banette',              types: ['ghost'],             spriteId: 354 },
  { name: 'Chimecho',             types: ['psychic'],           spriteId: 358 },
  { name: 'Absol',                types: ['dark'],              spriteId: 359 },
  { name: 'Glalie',               types: ['ice'],               spriteId: 362 },

  // ── Gen 4 ──────────────────────────────────────────────────────────────────
  { name: 'Torterra',             types: ['grass','ground'],    spriteId: 389 },
  { name: 'Infernape',            types: ['fire','fighting'],   spriteId: 392 },
  { name: 'Empoleon',             types: ['water','steel'],     spriteId: 395 },
  { name: 'Luxray',               types: ['electric'],          spriteId: 405 },
  { name: 'Roserade',             types: ['grass','poison'],    spriteId: 407 },
  { name: 'Rampardos',            types: ['rock'],              spriteId: 409 },
  { name: 'Bastiodon',            types: ['rock','steel'],      spriteId: 410 },
  { name: 'Lopunny',              types: ['normal'],            spriteId: 428 },
  { name: 'Spiritomb',            types: ['ghost','dark'],      spriteId: 442 },
  { name: 'Garchomp',             types: ['dragon','ground'],   spriteId: 445 },
  { name: 'Lucario',              types: ['fighting','steel'],  spriteId: 448 },
  { name: 'Hippowdon',            types: ['ground'],            spriteId: 450 },
  { name: 'Toxicroak',            types: ['poison','fighting'], spriteId: 454 },
  { name: 'Abomasnow',            types: ['grass','ice'],       spriteId: 460 },
  { name: 'Weavile',              types: ['dark','ice'],        spriteId: 461 },
  { name: 'Rhyperior',            types: ['ground','rock'],     spriteId: 464 },
  { name: 'Leafeon',              types: ['grass'],             spriteId: 470 },
  { name: 'Glaceon',              types: ['ice'],               spriteId: 471 },
  { name: 'Gliscor',              types: ['ground','flying'],   spriteId: 472 },
  { name: 'Mamoswine',            types: ['ice','ground'],      spriteId: 473 },
  { name: 'Gallade',              types: ['psychic','fighting'],spriteId: 475 },
  { name: 'Froslass',             types: ['ice','ghost'],       spriteId: 478 },
  { name: 'Rotom',                types: ['electric','ghost'],  spriteId: 479 },
  { name: 'Rotom-Heat',           types: ['electric','fire'],   spriteId: 10011 },
  { name: 'Rotom-Wash',           types: ['electric','water'],  spriteId: 10012 },
  { name: 'Rotom-Frost',          types: ['electric','ice'],    spriteId: 10013 },
  { name: 'Rotom-Fan',            types: ['electric','flying'], spriteId: 10014 },
  { name: 'Rotom-Mow',            types: ['electric','grass'],  spriteId: 10015 },

  // ── Gen 5 ──────────────────────────────────────────────────────────────────
  { name: 'Serperior',            types: ['grass'],             spriteId: 497 },
  { name: 'Emboar',               types: ['fire','fighting'],   spriteId: 500 },
  { name: 'Samurott',             types: ['water'],             spriteId: 503 },
  { name: 'Samurott-Hisui',       types: ['water','dark'],      spriteId: 503 },
  { name: 'Watchog',              types: ['normal'],            spriteId: 505 },
  { name: 'Liepard',              types: ['dark'],              spriteId: 510 },
  { name: 'Simisage',             types: ['grass'],             spriteId: 512 },
  { name: 'Simisear',             types: ['fire'],              spriteId: 514 },
  { name: 'Simipour',             types: ['water'],             spriteId: 516 },
  { name: 'Excadrill',            types: ['ground','steel'],    spriteId: 530 },
  { name: 'Audino',               types: ['normal'],            spriteId: 531 },
  { name: 'Conkeldurr',           types: ['fighting'],          spriteId: 534 },
  { name: 'Whimsicott',           types: ['grass','fairy'],     spriteId: 547 },
  { name: 'Krookodile',           types: ['ground','dark'],     spriteId: 553 },
  { name: 'Garbodor',             types: ['poison'],            spriteId: 569 },
  { name: 'Cofagrigus',           types: ['ghost'],             spriteId: 563 },
  { name: 'Zoroark',              types: ['dark'],              spriteId: 571 },
  { name: 'Zoroark-Hisui',        types: ['normal','ghost'],    spriteId: 571 },
  { name: 'Reuniclus',            types: ['psychic'],           spriteId: 579 },
  { name: 'Vanilluxe',            types: ['ice'],               spriteId: 584 },
  { name: 'Emolga',               types: ['electric','flying'], spriteId: 587 },
  { name: 'Chandelure',           types: ['ghost','fire'],      spriteId: 609 },
  { name: 'Beartic',              types: ['ice'],               spriteId: 614 },
  { name: 'Stunfisk',             types: ['ground','electric'], spriteId: 618 },
  { name: 'Stunfisk-Galarian',    types: ['ground','steel'],    spriteId: 10184 },
  { name: 'Golurk',               types: ['ground','ghost'],    spriteId: 623 },
  { name: 'Hydreigon',            types: ['dark','dragon'],     spriteId: 635 },
  { name: 'Volcarona',            types: ['bug','fire'],        spriteId: 637 },

  // ── Gen 6 ──────────────────────────────────────────────────────────────────
  { name: 'Chesnaught',           types: ['grass','fighting'],  spriteId: 652 },
  { name: 'Delphox',              types: ['fire','psychic'],    spriteId: 655 },
  { name: 'Greninja',             types: ['water','dark'],      spriteId: 658 },
  { name: 'Diggersby',            types: ['normal','ground'],   spriteId: 660 },
  { name: 'Talonflame',           types: ['fire','flying'],     spriteId: 663 },
  { name: 'Vivillon',             types: ['bug','flying'],      spriteId: 666 },
  { name: 'Floette',              types: ['fairy'],             spriteId: 669 },
  { name: 'Floette-Eternal',      types: ['fairy'],             spriteId: 10195 },
  { name: 'Florges',              types: ['fairy'],             spriteId: 671 },
  { name: 'Pangoro',              types: ['fighting','dark'],   spriteId: 675 },
  { name: 'Furfrou',              types: ['normal'],            spriteId: 676 },
  { name: 'Meowstic-M',           types: ['psychic'],           spriteId: 678 },
  { name: 'Meowstic-F',           types: ['psychic'],           spriteId: 10085 },
  { name: 'Aegislash',            types: ['steel','ghost'],     spriteId: 681 },
  { name: 'Aromatisse',           types: ['fairy'],             spriteId: 683 },
  { name: 'Slurpuff',             types: ['fairy'],             spriteId: 685 },
  { name: 'Clawitzer',            types: ['water'],             spriteId: 693 },
  { name: 'Heliolisk',            types: ['electric','normal'], spriteId: 695 },
  { name: 'Tyrantrum',            types: ['rock','dragon'],     spriteId: 697 },
  { name: 'Aurorus',              types: ['rock','ice'],        spriteId: 699 },
  { name: 'Sylveon',              types: ['fairy'],             spriteId: 700 },
  { name: 'Hawlucha',             types: ['fighting','flying'], spriteId: 701 },
  { name: 'Dedenne',              types: ['electric','fairy'],  spriteId: 702 },
  { name: 'Goodra',               types: ['dragon'],            spriteId: 706 },
  { name: 'Goodra-Hisui',         types: ['steel','dragon'],    spriteId: 706 },
  { name: 'Klefki',               types: ['steel','fairy'],     spriteId: 707 },
  { name: 'Trevenant',            types: ['ghost','grass'],     spriteId: 709 },
  { name: 'Gourgeist',            types: ['ghost','grass'],     spriteId: 711 },
  { name: 'Avalugg',              types: ['ice'],               spriteId: 713 },
  { name: 'Avalugg-Hisui',        types: ['ice','rock'],        spriteId: 713 },
  { name: 'Noivern',              types: ['flying','dragon'],   spriteId: 715 },

  // ── Gen 7 ──────────────────────────────────────────────────────────────────
  { name: 'Decidueye',            types: ['grass','ghost'],     spriteId: 724 },
  { name: 'Decidueye-Hisui',      types: ['grass','fighting'],  spriteId: 724 },
  { name: 'Incineroar',           types: ['fire','dark'],       spriteId: 727 },
  { name: 'Primarina',            types: ['water','fairy'],     spriteId: 730 },
  { name: 'Toucannon',            types: ['normal','flying'],   spriteId: 733 },
  { name: 'Crabominable',         types: ['fighting','ice'],    spriteId: 740 },
  { name: 'Lycanroc',             types: ['rock'],              spriteId: 745 },
  { name: 'Lycanroc-Midnight',    types: ['rock'],              spriteId: 10138 },
  { name: 'Lycanroc-Dusk',        types: ['rock'],              spriteId: 10152 },
  { name: 'Toxapex',              types: ['poison','water'],    spriteId: 748 },
  { name: 'Mudsdale',             types: ['ground'],            spriteId: 749 },
  { name: 'Araquanid',            types: ['water','bug'],       spriteId: 752 },
  { name: 'Salazzle',             types: ['poison','fire'],     spriteId: 758 },
  { name: 'Tsareena',             types: ['grass'],             spriteId: 763 },
  { name: 'Oranguru',             types: ['normal','psychic'],  spriteId: 765 },
  { name: 'Passimian',            types: ['fighting'],          spriteId: 766 },
  { name: 'Mimikyu',              types: ['ghost','fairy'],     spriteId: 778 },
  { name: 'Drampa',               types: ['normal','dragon'],   spriteId: 780 },
  { name: 'Kommo-o',              types: ['dragon','fighting'], spriteId: 784 },

  // ── Gen 8 ──────────────────────────────────────────────────────────────────
  { name: 'Corviknight',          types: ['flying','steel'],    spriteId: 823 },
  { name: 'Flapple',              types: ['grass','dragon'],    spriteId: 841 },
  { name: 'Appletun',             types: ['grass','dragon'],    spriteId: 842 },
  { name: 'Sandaconda',           types: ['ground'],            spriteId: 844 },
  { name: 'Polteageist',          types: ['ghost'],             spriteId: 855 },
  { name: 'Hatterene',            types: ['psychic','fairy'],   spriteId: 858 },
  { name: 'Mr. Rime',             types: ['ice','psychic'],     spriteId: 866 },
  { name: 'Runerigus',            types: ['ground','ghost'],    spriteId: 867 },
  { name: 'Alcremie',             types: ['fairy'],             spriteId: 869 },
  { name: 'Morpeko',              types: ['electric','dark'],   spriteId: 877 },
  { name: 'Dragapult',            types: ['dragon','ghost'],    spriteId: 887 },

  // ── Hisui ──────────────────────────────────────────────────────────────────
  { name: 'Wyrdeer',              types: ['normal','psychic'],  spriteId: 899 },
  { name: 'Kleavor',              types: ['bug','rock'],        spriteId: 900 },
  { name: 'Basculegion',          types: ['water','ghost'],     spriteId: 901 },
  { name: 'Basculegion-F',        types: ['water','ghost'],     spriteId: 901 },
  { name: 'Sneasler',             types: ['poison','fighting'], spriteId: 902 },

  // ── Gen 9 ──────────────────────────────────────────────────────────────────
  { name: 'Meowscarada',          types: ['grass','dark'],      spriteId: 908 },
  { name: 'Skeledirge',           types: ['fire','ghost'],      spriteId: 911 },
  { name: 'Quaquaval',            types: ['water','fighting'],  spriteId: 914 },
  { name: 'Maushold',             types: ['normal'],            spriteId: 925 },
  { name: 'Garganacl',            types: ['rock'],              spriteId: 934 },
  { name: 'Armarouge',            types: ['fire','psychic'],    spriteId: 936 },
  { name: 'Ceruledge',            types: ['fire','ghost'],      spriteId: 937 },
  { name: 'Bellibolt',            types: ['electric'],          spriteId: 939 },
  { name: 'Scovillain',           types: ['grass','fire'],      spriteId: 952 },
  { name: 'Espathra',             types: ['psychic','flying'],  spriteId: 956 },
  { name: 'Tinkaton',             types: ['fairy','steel'],     spriteId: 959 },
  { name: 'Palafin',              types: ['water'],             spriteId: 964 },
  { name: 'Orthworm',             types: ['steel'],             spriteId: 968 },
  { name: 'Glimmora',             types: ['rock','poison'],     spriteId: 970 },
  { name: 'Farigiraf',            types: ['normal','psychic'],  spriteId: 981 },
  { name: 'Kingambit',            types: ['dark','steel'],      spriteId: 983 },
  { name: 'Sinistcha',            types: ['grass','ghost'],     spriteId: 1013 },
  { name: 'Archaludon',           types: ['dragon','steel'],    spriteId: 1018 },
  { name: 'Hydrapple',            types: ['grass','dragon'],    spriteId: 1019 },
]